# This workflow will do a clean install of node dependencies, cache/restore them and run tests

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload code coverage to GitHub
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074
        with:
          name: code-coverage
          path: code/coverage/lcov.info}

  coverage_report:
    name: Generate coverage report
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download previous code coverage
        uses: actions/download-artifact@v2
        with:
          name: code-coverage
          path: coverage

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1.3.2
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 90
          artifact-name: code-coverage
          github-token: ${{ secrets.GITHUB_TOKEN }
