# This workflow will do a clean install of node dependencies, cache/restore them, build application and run tests

name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload code coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          files: coverage/lcov.info

      - name: Lint code
        run: npm run lint:ci

      - name: Check code style with prettier
        run: npm run format:ci
